import 'package:easy_localization/easy_localization.dart';

final List<String> noticeKinds = [
  tr('notice.all'),
  tr('notice.universityAdmissionNotice'),
  tr('notice.graduateAdmissionNotice'),
  tr('notice.academicNotice'),
  tr('notice.specialLectureNotice'),
  tr('notice.administrativeNotice'),
  tr('notice.scholarshipNotice'),
  tr('notice.socialService'),
  tr('notice.contestEvent'),
  tr('notice.swAcademicNotice'),
  tr('notice.swEmploymentNotice'),
  tr('notice.swScholarshipNotice'),
  tr('notice.swSpecialLectureEventNotice'),
  tr('notice.internalRecruitment'),
  tr('notice.libraryNotice'),
  tr('notice.studentCouncilNotice'),
  tr('notice.graduationPreparationCommitteeNotice'),
  tr('notice.dormitoryNotice'),
  tr('notice.systemNotice'),
  tr('notice.internationalStudentAcademicNotice'),
  tr('notice.internationalStudentVisaNotice'),
  tr('notice.internationalStudentScholarshipNotice'),
  tr('notice.internationalStudentEventEmploymentNotice'),
  tr('notice.internationalStudentSupportNotice'),
  tr('notice.governmentInvitedInternationalStudentNotice')
];

final Map<String, String> noticeMapperEnToKo = {
  "all": "전체",
  "universityAdmissionNotice": "대학입학공지",
  "graduateAdmissionNotice": "대학원입학공지",
  "academicNotice": "학사공지",
  "specialLectureNotice": "특강공지",
  "administrativeNotice": "행정공지",
  "scholarshipNotice": "장학공지",
  "socialService": "사회봉사",
  "contestEvent": "공모∙행사",
  "swAcademicNotice": "SW 학사공지",
  "swEmploymentNotice": "SW 취업공지",
  "swScholarshipNotice": "SW 장학공지",
  "swSpecialLectureEventNotice": "SW 특강/행사공지",
  "internalRecruitment": "교내채용",
  "libraryNotice": "도서관 공지",
  "studentCouncilNotice": "총학생회 공지",
  "graduationPreparationCommitteeNotice": "졸준위 공지",
  "dormitoryNotice": "생활관 공지",
  "systemNotice": "시스템공지",
  "internationalStudentAcademicNotice": "유학생 학사공지",
  "internationalStudentVisaNotice": "유학생 비자공지",
  "internationalStudentScholarshipNotice": "유학생 장학공지",
  "internationalStudentEventEmploymentNotice": "유학생 행사/취업공지",
  "internationalStudentSupportNotice": "유학생 학생지원공지",
  "governmentInvitedInternationalStudentNotice": "유학생 정부초청공지"
};

final Map<String, String> noticeMapperZhToKo = {
  "全部": "전체",
  "大学入学通知": "대학입학공지",
  "研究生入学通知": "대학원입학공지",
  "学术通知": "학사공지",
  "特别讲座通知": "특강공지",
  "行政通知": "행정공지",
  "奖学金通知": "장학공지",
  "社会服务": "사회봉사",
  "比赛/活动": "공모∙행사",
  "软件学术通知": "SW 학사공지",
  "软件就业通知": "SW 취업공지",
  "软件奖学金通知": "SW 장학공지",
  "软件特别讲座/活动通知": "SW 특강/행사공지",
  "校内招聘": "교내채용",
  "图书馆通知": "도서관 공지",
  "学生会通知": "총학생회 공지",
  "毕业准备委员会通知": "졸준위 공지",
  "宿舍通知": "생활관 공지",
  "系统通知": "시스템공지",
  "国际学生学术通知": "유학생 학사공지",
  "国际学生签证通知": "유학생 비자공지",
  "国际学生奖学金通知": "유학생 장학공지",
  "国际学生活动/就业通知": "유학생 행사/취업공지",
  "国际学生支持通知": "유학생 학생지원공지",
  "政府邀请国际学生通知": "유학생 정부초청공지"
};

final Map<String, String> noticeMapperKoToEn = {
  "전체": "all",
  "대학입학공지": "universityAdmissionNotice",
  "대학원입학공지": "graduateAdmissionNotice",
  "학사공지": "academicNotice",
  "특강공지": "specialLectureNotice",
  "행정공지": "administrativeNotice",
  "장학공지": "scholarshipNotice",
  "사회봉사": "socialService",
  "공모∙행사": "contestEvent",
  "SW 학사공지": "swAcademicNotice",
  "SW 취업공지": "swEmploymentNotice",
  "SW 장학공지": "swScholarshipNotice",
  "SW 특강/행사공지": "swSpecialLectureEventNotice",
  "교내채용": "internalRecruitment",
  "도서관 공지": "libraryNotice",
  "총학생회 공지": "studentCouncilNotice",
  "졸준위 공지": "graduationPreparationCommitteeNotice",
  "생활관 공지": "dormitoryNotice",
  "시스템공지": "systemNotice",
  "유학생 학사공지": "internationalStudentAcademicNotice",
  "유학생 비자공지": "internationalStudentVisaNotice",
  "유학생 장학공지": "internationalStudentScholarshipNotice",
  "유학생 행사/취업공지": "internationalStudentEventEmploymentNotice",
  "유학생 학생지원공지": "internationalStudentSupportNotice",
  "유학생 정부초청공지": "governmentInvitedInternationalStudentNotice"
};

final Map<String, String> noticeMapperKoToZh = {
  "all": "全部",
  "대학입학공지": "大学入学通知",
  "대학원입학공지": "研究生入学通知",
  "학사공지": "学术通知",
  "특강공지": "特别讲座通知",
  "행정공지": "行政通知",
  "장학공지": "奖学金通知",
  "사회봉사": "社会服务",
  "공모∙행사": "比赛/活动",
  "SW 학사공지": "软件学术通知",
  "SW 취업공지": "软件就业通知",
  "SW 장학공지": "软件奖学金通知",
  "SW 특강/행사공지": "软件特别讲座/活动通知",
  "교내채용": "校内招聘",
  "도서관 공지": "图书馆通知",
  "총학생회 공지": "学生会通知",
  "졸준위 공지": "毕业准备委员会通知",
  "생활관 공지": "宿舍通知",
  "시스템공지": "系统通知",
  "유학생 학사공지": "国际学生学术通知",
  "유학생 비자공지": "国际学生签证通知",
  "유학생 장학공지": "国际学生奖学金通知",
  "유학생 행사/취업공지": "国际学生活动/就业通知",
  "유학생 학생지원공지": "国际学生支持通知",
  "유학생 정부초청공지": "政府邀请国际学生通知"
};
