import 'package:easy_localization/easy_localization.dart';

final List<String> noticeKinds = [
  tr('notice.all'),
  tr('notice.universityAdmissionNotice'),
  tr('notice.graduateAdmissionNotice'),
  tr('notice.academicNotice'),
  tr('notice.specialLectureNotice'),
  tr('notice.administrativeNotice'),
  tr('notice.scholarshipNotice'),
  tr('notice.socialService'),
  tr('notice.contestEvent'),
  tr('notice.swAcademicNotice'),
  tr('notice.swEmploymentNotice'),
  tr('notice.swScholarshipNotice'),
  tr('notice.swSpecialLectureEventNotice'),
  tr('notice.internalRecruitment'),
  tr('notice.libraryNotice'),
  tr('notice.studentCouncilNotice'),
  tr('notice.graduationPreparationCommitteeNotice'),
  tr('notice.dormitoryNotice'),
  tr('notice.systemNotice'),
  tr('notice.internationalStudentAcademicNotice'),
  tr('notice.internationalStudentVisaNotice'),
  tr('notice.internationalStudentScholarshipNotice'),
  tr('notice.internationalStudentEventEmploymentNotice'),
  tr('notice.internationalStudentSupportNotice'),
  tr('notice.governmentInvitedInternationalStudentNotice')
];

final Map<String, String> noticeMapperEnToKo = {
  "All": "전체",
  "University Admission": "대학입학공지",
  "Graduate Admission": "대학원입학공지",
  "Academic": "학사공지",
  "Special Lecture": "특강공지",
  "Administrative": "행정공지",
  "Scholarship": "장학공지",
  "Social Service": "사회봉사",
  "Contest Event": "공모∙행사",
  "SW Academic": "SW 학사공지",
  "SW Employment": "SW 취업공지",
  "SW Scholarship": "SW 장학공지",
  "SW Special Lecture Event": "SW 특강/행사공지",
  "Internal Recruitment": "교내채용",
  "Library": "도서관 공지",
  "Student Council": "총학생회 공지",
  "Graduation Preparation Committee": "졸준위 공지",
  "Dormitory": "생활관 공지",
  "System": "시스템공지",
  "International Student Academic": "유학생 학사공지",
  "International Student Visa": "유학생 비자공지",
  "International Student Scholarship": "유학생 장학공지",
  "International Student Employment": "유학생 행사/취업공지",
  "International Student Support": "유학생 학생지원공지",
  "Government International Student": "유학생 정부초청공지"
};

final Map<String, String> noticeMapperZhToKo = {
  "全部": "전체",
  "大学入学通知": "대학입학공지",
  "研究生入学通知": "대학원입학공지",
  "学术通知": "학사공지",
  "特别讲座通知": "특강공지",
  "行政通知": "행정공지",
  "奖学金通知": "장학공지",
  "社会服务": "사회봉사",
  "比赛/活动": "공모∙행사",
  "软件学术通知": "SW 학사공지",
  "软件就业通知": "SW 취업공지",
  "软件奖学金通知": "SW 장학공지",
  "软件特别讲座/活动通知": "SW 특강/행사공지",
  "校内招聘": "교내채용",
  "图书馆通知": "도서관 공지",
  "学生会通知": "총학생회 공지",
  "毕业准备委员会通知": "졸준위 공지",
  "宿舍通知": "생활관 공지",
  "系统通知": "시스템공지",
  "国际学生学术通知": "유학생 학사공지",
  "国际学生签证通知": "유학생 비자공지",
  "国际学生奖学金通知": "유학생 장학공지",
  "国际学生活动/就业通知": "유학생 행사/취업공지",
  "国际学生支持通知": "유학생 학생지원공지",
  "政府邀请国际学生通知": "유학생 정부초청공지"
};

final Map<String, String> noticeMapperKoToEn = {
  "전체": "All",
  "대학입학공지": "University Admission",
  "대학원입학공지": "Graduate Admission",
  "학사공지": "Academic",
  "특강공지": "Special Lecture",
  "행정공지": "Administrative",
  "장학공지": "Scholarship",
  "사회봉사": "Social Service",
  "공모∙행사": "Contest Event",
  "SW 학사공지": "SW Academic",
  "SW 취업공지": "SW Employment",
  "SW 장학공지": "SW Scholarship",
  "SW 특강/행사공지": "SW Special Lecture Event",
  "교내채용": "Internal Recruitment",
  "도서관 공지": "Library",
  "총학생회 공지": "Student Council",
  "졸준위 공지": "Graduation Preparation Committee",
  "생활관 공지": "Dormitory",
  "시스템공지": "System",
  "유학생 학사공지": "International Student Academic",
  "유학생 비자공지": "International Student Visa",
  "유학생 장학공지": "International Student Scholarship",
  "유학생 행사/취업공지": "International Student Employment",
  "유학생 학생지원공지": "International Student Support",
  "유학생 정부초청공지": "Government International Student"
};

final Map<String, String> noticeMapperKoToZh = {
  "all": "全部",
  "대학입학공지": "大学入学通知",
  "대학원입학공지": "研究生入学通知",
  "학사공지": "学术通知",
  "특강공지": "特别讲座通知",
  "행정공지": "行政通知",
  "장학공지": "奖学金通知",
  "사회봉사": "社会服务",
  "공모∙행사": "比赛/活动",
  "SW 학사공지": "软件学术通知",
  "SW 취업공지": "软件就业通知",
  "SW 장학공지": "软件奖学金通知",
  "SW 특강/행사공지": "软件特别讲座/活动通知",
  "교내채용": "校内招聘",
  "도서관 공지": "图书馆通知",
  "총학생회 공지": "学生会通知",
  "졸준위 공지": "毕业准备委员会通知",
  "생활관 공지": "宿舍通知",
  "시스템공지": "系统通知",
  "유학생 학사공지": "国际学生学术通知",
  "유학생 비자공지": "国际学生签证通知",
  "유학생 장학공지": "国际学生奖学金通知",
  "유학생 행사/취업공지": "国际学生活动/就业通知",
  "유학생 학생지원공지": "国际学生支持通知",
  "유학생 정부초청공지": "政府邀请国际学生通知"
};
