final Map<String, List<String>> collegeInfo = {
  'korean': [
    '글로벌인문ㆍ지역대학',
    '사회과학대학',
    '법과대학',
    '경상대학',
    '창의공과대학',
    '조형대학',
    '과학기술대학',
    '예술대학',
    '체육대학',
    '경영대학',
    '소프트웨어융합대학',
    '건축대학',
    '자동차융합대학',
    '미래모빌리티학과',
    '교양대학',
    '교직과정부',
    '인문기술융합학부'
  ],
  'english': [
    'Global College of Humaities and Area Studies',
    'College of Social Sciences',
    'College of Law',
    'College of Economics & Commerce',
    'College of Creative Engineering',
    "College of Design",
    'College of Science and Technology',
    'College of Arts',
    'College of Physical Education',
    'College of Business Adminstration',
    'College of Computer Science',
    'College of Architecture',
    'College of Automotive Engineering',
    'College of Future Mobility',
    'College of General Education',
    'Department of Teaching Profession',
    'School of Humanities, Art & Technology',
  ],
};

final Map<String, List<List<String>>> departmentInfo = {
  'korean': [
    [
      '한국어문학부',
      '영어영문학부',
      '중국학부',
      '한국역사학과',
    ],
    [
      '행정학과',
      '정치외교학과',
      '사회학과',
      '미디어ㆍ광고학부',
      '교육학과',
      '러시아ㆍ유라시아학과',
      '일본학과',
      '글로벌기후환경융합학부',
      '행정관리학과',
    ],
    [
      '법학부',
      '기업융합법학과',
    ],
    [
      '경제학과',
      '국제통상학과',
    ],
    [
      '신소재공학부',
      '기계공학부',
      '건설시스템공학부',
      '전자공학부',
      '양자보안차세대통신학부',
    ],
    [
      '공업디자인학과',
      '시각디자인학과',
      '금속공예학과',
      '도자공예학과',
      '의상디자인학과',
      '공간디자인학과',
      '영상디자인학과',
      '자동차ㆍ운송디자인학과',
      'AI디자인학과',
    ],
    [
      '산림환경시스템학과',
      '임산생명공학과',
      '나노전자물리학과',
      '응용화학부',
      '식품영양학과',
      '정보보안암호수학과',
      '바이오발효융합학과',
    ],
    [
      '음악학부',
      '미술학부',
      '공연예술학부',
    ],
    [
      '스포츠교육학과',
      '스포츠산업레저학과',
      '스포츠건강재활학과',
    ],
    [
      '경영학부',
      '경영정보학부',
      'KMU International Business School',
      '재무금융ㆍ회계학부',
      'AI빅데이터융합경영학과',
      '기업경영학부',
    ],
    [
      '소프트웨어학부',
      '인공지능학부',
    ],
    [
      '건축학부',
    ],
    [
      '자동차공학과',
      '자동차IT융합학과',
      '미래자동차학부',
    ],
    ['미래모빌리티학과'],
    ['교양대학'],
    ['교직과정부'],
    ['인문기술융합부'],
  ],
  'english': [
    [
      'Department of Korean Language and Literature',
      'Department of English Language and Literature',
      'Department of Chinese',
      'Department of Korean History'
    ],
    [
      'Department of Public Administration',
      'Department of Political Science and Diplomacy',
      'Department of Sociology',
      'Department of Media and Advertising',
      'Department of Education',
      'Department of Russian and Eurasian Studies',
      'Department of Japanese',
      'School of Global Climate and Environmental Convergence',
      'Department of Public Administration',
    ],
    [
      'Department of Law',
      'Department of Corporate Law and Business',
    ],
    [
      'Department of Economics',
      'Department of International Trade',
    ],
    [
      'Department of Materials Science and Engineering',
      'Department of Mechanical Engineering',
      'Department of Construction Systems Engineering',
      'Department of Electronic Engineering',
      'Department of Quantum Security and Next Generation Communication',
    ],
    [
      'Department of Industrial Design',
      'Department of Visual Design',
      'Department of Metal Crafts',
      'Department of Ceramic Arts',
      'Department of Fashion Design',
      'Department of Spatial Design',
      'Department of Visual Media Design',
      'Department of Automotive and Transportation Design',
      'Department of AI Design',
    ],
    [
      'Department of Forest Environmental Systems',
      'Department of Reproductive Life Engineering',
      'Department of Nano Electronic Physics',
      'Department of Applied Chemistry',
      'Department of Food and Nutrition',
      'Department of Information Security and Cryptographic Mathematics',
      'Department of Bio Fermentation Convergence',
    ],
    [
      'Department of Music',
      'Department of Fine Arts',
      'Department of Performing Arts',
    ],
    [
      'Department of Sports Education',
      'Department of Sports Industry and Leisure Studies',
      'Department of Sports Health Rehabilitation',
    ],
    [
      'School of Business Administration',
      'Department of Business Information',
      'KMU International Business School',
      'Department of Financial Finance and Accounting',
      'Department of AI Big Data Convergence Management',
      'Department of Corporate Management',
    ],
    [
      'Department of Software',
      'Department of Artificial Intelligence',
    ],
    [
      'Department of Architecture',
    ],
    [
      'Department of Automotive Engineering',
      'Department of Automotive IT Convergence',
      'Department of Future Automotive',
    ],
    [
      'Department of Future Mobility',
    ],
    [
      'College of General Education',
    ],
    [
      'Department of Teaching Profession',
    ],
    [
      'School of Humanities, Art & Technology',
    ],
  ]
};
