FROM python:3.10

COPY . /ai
WORKDIR /ai

RUN pip install fastapi uvicorn python-multipart
RUN pip install -r requirements.txt


EXPOSE 8080

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]