// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkihJE32WAKgZMgjYlM2L9c0RZvExTVDI',
    appId: '1:452949760750:web:908266d0f72617a80bb1ff',
    messagingSenderId: '452949760750',
    projectId: 'kmu-capstone30',
    authDomain: 'kmu-capstone30.firebaseapp.com',
    storageBucket: 'kmu-capstone30.appspot.com',
    measurementId: 'G-3GZE891DW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMRgiGjf9KX1EEqRSCnzmTPrFY9U-Fwc',
    appId: '1:452949760750:android:2304470e3a79a1af0bb1ff',
    messagingSenderId: '452949760750',
    projectId: 'kmu-capstone30',
    storageBucket: 'kmu-capstone30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE1QB9ujL-VDO0XnWGFOe1uvdLccBsIdQ',
    appId: '1:452949760750:ios:d05c107ef8dbc6250bb1ff',
    messagingSenderId: '452949760750',
    projectId: 'kmu-capstone30',
    storageBucket: 'kmu-capstone30.appspot.com',
    iosBundleId: 'com.example.capstoneFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE1QB9ujL-VDO0XnWGFOe1uvdLccBsIdQ',
    appId: '1:452949760750:ios:708753e0544b37f80bb1ff',
    messagingSenderId: '452949760750',
    projectId: 'kmu-capstone30',
    storageBucket: 'kmu-capstone30.appspot.com',
    iosBundleId: 'com.example.capstoneFront.RunnerTests',
  );
}
